# Generated by Django 2.2.6 on 2019-10-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrption',
            new_name='description',
        ),
    ]
